services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: schulung-openldap
    hostname: openldap
    environment:
      LDAP_ORGANISATION: "Schulung GmbH"
      LDAP_DOMAIN: "schulung.local"
      LDAP_BASE_DN: "dc=schulung,dc=local"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
    ports:
      - "389:389"
      - "8389:389"
      - "636:636"
    volumes:
      - ./bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: "--copy-service"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: schulung-phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8888:80"
    depends_on:
      - openldap

volumes:
  ldap_data:
  ldap_config:


